### ISSUE TITLE
Replace deprecated mpd lib

### ISSUE THREAD

**Issue by sabl0r** [NoyaInRain/wall#5]
py-libmpdclient2 is deprecated.

> This library is not maintained and has been superceded by the python-mpd library. New projects should use python-mpd. (http://incise.org/py-libmpdclient2.html)

But python-mpd is outdated, too.
Use python-mpd2 instead: https://github.com/Mic92/python-mpd2

**Comment by NoyaInRain** [comment]
Tracked by #103 .
